name: Commit Check
on: [push, pull_request]

jobs:
  commit-check:
    name: Commit Check
    runs-on: ubuntu-latest
    steps:
      - uses: IceflowRE/gitcc@v2
        with:
          validator: SimpleTag
